### PR TITLE
class_sortableListing: Remove superfluous get_post() call from_ save_…

### PR DESCRIPTION
**Pull request by sunweaver**
…object()

### CODE REVIEW

**Comment by master-caster** [comment]
@sunweaver The following code block commented with **// Edit requested?** contains
an useless **get_post()** too. We should remove this in one step.
Despite this, i prefer something like this
`foreach(array_keys($_POST) as $key) `
so you see directly, that only the keys are used in this loop.

**Review by master-caster — CHANGES_REQUESTED** [review]
@sunweaver The following code block commented with // Edit requested? contains
an useless get_post() too. We should remove this in one step.
Despite this, i prefer something like this
foreach(array_keys($_POST) as $key)
so you see directly, that only the keys are used in this loop.

**Comment by c-schwamborn** [comment]
You're correct in both points. Can you change those three lines?

**Comment by master-caster** [comment]
Updated the code.

See 66a9e4194099c621053f55f1c155b8c280374440

**Pull request closed without merging**
